services:
  {{ service_name }}:
    container_name: {{ service_name }}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: {% raw %}${{% endraw %}{{ restart_variable }}{% raw %}}{% endraw %}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      {%- for v in volumes %}
      - {{ v }}
      {%- endfor %}